### ISSUE TITLE
Still sends no image

### ISSUE THREAD

**Issue by Grey-Wolf-PO** [CreaturePhil/dem-feels#2]
When using your code:

demFeels.extendEmotes({
  'feelsnew': 'feelsnew.png'
});

Does not work when reformatted for my custom emotes, Still returns no image when used in file.

**Comment by CreaturePhil** [comment]
Are you using the latest version of dem feels ``v1.6.0 ``?

**Comment by Grey-Wolf-PO** [comment]
probs not
