### ISSUE TITLE
Your node package is still failing to work after SO MANY UPDATES

### ISSUE THREAD

**Issue by Chirou-Cat** [CreaturePhil/dem-feels#3]
...AND IT STILL WONT SHOW THANKS TO YOUR NICE USELESS PACKAGE

FIX IT OR TELL ME HOW IT USED TO RUN IN THE OLD ARRAY

**Comment by CreaturePhil** [comment]
If regarding Showdown-Boilerplate, then make sure you have the newest version of dem-feels which is v1.6.0. It was using v1.3.0 but I just updated it to the newest version via https://github.com/CreaturePhil/Showdown-Boilerplate/commit/d38b59708bc82a6b715d33ed05138806b8e918f6.
